### ISSUE TITLE
what should be the contents of cmdline.txt file

### ISSUE THREAD

**Issue by Anzal3c3** [sinandredemption/ota_update#1]
i am trying to run the script and its giving error "Unknown active partition"

**Comment by sinandredemption** [comment]
Hello @Anzal3c3 

Have you followed the prerequisite instrictions on the README.md file and made the partition structure as required by the scripts?

If not, feel free to ask help.

**Comment by Anzal3c3** [comment]
yes already created

**Comment by sinandredemption** [comment]
Can you let me know the steps to reproduce your issue? Thanks.

**Comment by Anzal3c3** [comment]
thanks for the support issue got resolved
